'''
fcsxmlparser
reads xml file generated by ZEN macro in automatic FCS pipeline
show image with points where FCS has been acquired. 
Optionally one can specify which channel to show, base 1
	./ImageJ-win64.exe -macro path_to_fcsxmlparser 'xmlfilename'
    ./ImageJ-win64.exe -macro path_to_fcsxmlparser 'xmlfilename -cchannelNr'

EMBL, March, 2015
Antonio Politi
'''


import ij
import re
from ij.gui import PointRoi
from ij.plugin.frame import RoiManager
from loci.plugins import BF
import os
from ij import IJ, ImagePlus
from xml.etree import ElementTree as ET



def getPosition(root):
	''' Parse xml file for position of points and imgName. Returns a dictionary and imgName'''
	obj = {}
	for child in root:
		if child.tag == 'Image':
			imgName = os.path.join(os.path.dirname(xmlfile), os.path.basename(child.attrib['Name']))
			#legacy code
			fileName, fileExtension = os.path.splitext(imgName)
			if not fileExtension == '.czi' or not fileExtension == '.lsm':
				imgName = imgName + ".lsm"
		if child.tag == 'object':
			pos = [0, 0, 0]
			for nef in child:
				if nef.tag == 'x':
					pos[0] = int(nef.text)
				if nef.tag == 'y':
					pos[1] = int(nef.text)
				if nef.tag == 'z':
					pos[2] = int(nef.text)
			obj[int(child.attrib['ID'])] = pos
	return obj, imgName

#close all open files and clean roimanager
roim = RoiManager.getInstance()
if roim is None:
	roim = RoiManager()
IJ.run("Close All")
IJ.run("Clear Results")
try:
	roim.reset()
except AttributeError:
	roim.runCommand("reset")
	
#read argument when called from command line
try:
	arg = getArgument()
except:
	IJ.log(" ")
	IJ.log("Error in loading the file! Using default file!")
	IJ.log("Run macroscript: ./ImageJ-win64.exe -macro fcsxmlparser 'xmlfilename'")
	IJ.log("or               ./ImageJ-win64.exe -macro fcsxmlparser 'xmlfilename -cchannelNr'")
	arg = 'X:\\AntonioP_t2\\RLadurner_JMPeters\\DoubleArrest\\150212_STAG2\\Mitosys2\\LSM\\DE_W0001_P0001\\DE_2_W0001_P0001_T0001\\TR1_W0001_P0001\\TR1_2_W0001_P0001_T0001.xml -c2'

#split for channel argument
arg = re.split('\s+-c', arg)
if len(arg)>1:
	xmlfile = arg[0]
	ch = int(arg[1])
else:
	xmlfile = arg[0]
	ch = 1

#open xml file and parse it
tree = ET.parse(xmlfile)
root = tree.getroot()
obj, imgName = getPosition(root)
print imgName

#open image
img =  BF.openImagePlus(imgName)[0] 
img.setZ(obj[1][2]+1)
img.setC(int(ch))
img.show()


#draw rois
for i in range(1, len(obj)+1):
	PR = PointRoi(obj[i][0],obj[i][1])
	try:
		PR.setSize(3)
		PR.setPointType(0)
		roim.addRoi(PR)
	except:
		roim.addRoi(PR)

roim.runCommand('Show All with Labels')



